# Generated by Django 4.1.5 on 2023-02-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acteur',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='duree_minutes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(choices=[('ACTION', 'ACTION'), ('COMEDIE', 'COMEDIE'), ('DRAME', 'DRAME'), ('HORREUR', 'HORREUR')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='realisateur',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='realisateur',
            name='pays',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
