# Generated by Django 4.1.5 on 2023-02-16 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp1', '0002_alter_acteur_age_alter_film_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='film',
        ),
        migrations.CreateModel(
            name='Jouer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp1.acteur')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp1.film')),
            ],
        ),
        migrations.AddField(
            model_name='acteur',
            name='films',
            field=models.ManyToManyField(through='myApp1.Jouer', to='myApp1.film'),
        ),
    ]
