# Generated by Django 4.1.5 on 2023-02-16 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp1', '0004_scenario_film_alter_film_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('dateCreationCompte', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='estAuCinema',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='film',
            name='notation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='realisateur',
            name='ville',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='estEnEcriture',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Emprunter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePret', models.DateTimeField(auto_now_add=True)),
                ('dateRetour', models.DateTimeField(null=True)),
                ('estRendu', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp1.client')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp1.film')),
            ],
        ),
    ]
